import { ThemeProvider } from "@/contexts/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "@/app/globals.css";

const open_sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="scroll-smooth" suppressHydrationWarning>
			<body className={open_sans.className}>
				<ClerkProvider
					appearance={{
						variables: { colorPrimary: "#000000" },
						elements: {
							formButtonPrimary:
								"bg-black border border-black border-solid hover:bg-white hover:text-black",
							socialButtonsBlockButton:
								"bg-white border-gray-200 hover:bg-transparent hover:border-black text-gray-600 hover:text-black",
							socialButtonsBlockButtonText: "font-semibold",
							formButtonReset:
								"bg-white border border-solid border-gray-200 hover:bg-transparent hover:border-black text-gray-500 hover:text-black",
							membersPageInviteButton:
								"bg-black border border-black border-solid hover:bg-white hover:text-black",
							card: "bg-[#fafafa]",
						},
					}}
				>
					<ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false} storageKey="discord-clone-theme" disableTransitionOnChange>
						{children}
					</ThemeProvider>
				</ClerkProvider>
			</body>
		</html>
	);
}
